// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AverageVote: typeof import('./components/AverageVote.vue')['default']
    ComboBox: typeof import('./components/ComboBox.vue')['default']
    'Icon:ic:baselineSettings': typeof import('~icons/ic/baseline-settings')['default']
    'Icon:lineMd:chevronLeft': typeof import('~icons/line-md/chevron-left')['default']
    'Icon:lineMd:circleToConfirmCircleTransition': typeof import('~icons/line-md/circle-to-confirm-circle-transition')['default']
    'Icon:lineMd:coffeeFilled': typeof import('~icons/line-md/coffee-filled')['default']
    'Icon:lineMd:confirmCircleToCircleTransition': typeof import('~icons/line-md/confirm-circle-to-circle-transition')['default']
    'Icon:lineMd:githubLoop': typeof import('~icons/line-md/github-loop')['default']
    'Icon:lineMd:loadingTwotoneLoop': typeof import('~icons/line-md/loading-twotone-loop')['default']
    'Icon:lineMd:sunnyFilledLoop': typeof import('~icons/line-md/sunny-filled-loop')['default']
    'Icon:lineMd:sunnyFilledLoopToMoonFilledLoopTransition': typeof import('~icons/line-md/sunny-filled-loop-to-moon-filled-loop-transition')['default']
    'Icon:mdi:close': typeof import('~icons/mdi/close')['default']
    'Icon:mdi:coffee': typeof import('~icons/mdi/coffee')['default']
    'Icon:mdi:eye': typeof import('~icons/mdi/eye')['default']
    ItsToast: typeof import('./components/ItsToast.vue')['default']
    LoadingTable: typeof import('./components/LoadingTable.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionNotFound: typeof import('./components/SessionNotFound.vue')['default']
    TestMe: typeof import('./components/TestMe.vue')['default']
    TheButtons: typeof import('./components/TheButtons.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheObservers: typeof import('./components/TheObservers.vue')['default']
    TheTable: typeof import('./components/TheTable.vue')['default']
    TheToggle: typeof import('./components/TheToggle.vue')['default']
    UserConnection: typeof import('./components/UserConnection.vue')['default']
    VoteCards: typeof import('./components/VoteCards.vue')['default']
    VoteResults: typeof import('./components/VoteResults.vue')['default']
  }
}
