/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AverageVote: typeof import('./components/AverageVote.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    BaseUserForm: typeof import('./components/BaseUserForm.vue')['default']
    BuyMeACoffee: typeof import('./components/icons/BuyMeACoffee.vue')['default']
    BuyMeACoffeeDark: typeof import('./components/icons/BuyMeACoffeeDark.vue')['default']
    ComboBox: typeof import('./components/ComboBox.vue')['default']
    DeleteUserBtn: typeof import('./components/DeleteUserBtn.vue')['default']
    FormButton: typeof import('./components/FormButton.vue')['default']
    GenericToggle: typeof import('./components/GenericToggle.vue')['default']
    ItsToast: typeof import('./components/ItsToast.vue')['default']
    JoinWithNewUser: typeof import('./components/JoinWithNewUser.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    LoadingTable: typeof import('./components/LoadingTable.vue')['default']
    NumberVoteResults: typeof import('./components/results/NumberVoteResults.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionNotFound: typeof import('./components/SessionNotFound.vue')['default']
    ShirtAverageVote: typeof import('./components/results/ShirtAverageVote.vue')['default']
    ShirtProgressBar: typeof import('./components/results/ShirtProgressBar.vue')['default']
    ShirtVoteResults: typeof import('./components/results/ShirtVoteResults.vue')['default']
    TableActionBtn: typeof import('./components/TableActionBtn.vue')['default']
    TheButtons: typeof import('./components/TheButtons.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheObservers: typeof import('./components/TheObservers.vue')['default']
    TheTable: typeof import('./components/TheTable.vue')['default']
    ToggleUserModeBtn: typeof import('./components/ToggleUserModeBtn.vue')['default']
    UserConnection: typeof import('./components/UserConnection.vue')['default']
    UsernameInput: typeof import('./components/UsernameInput.vue')['default']
    VoteCards: typeof import('./components/VoteCards.vue')['default']
    VoteResults: typeof import('./components/VoteResults.vue')['default']
  }
}
